/**
 * 전국 라멘 지도 UI를 위한 창작 데모 데이터입니다.
 * 아래 매장명, 주소, 메뉴, 가격, 평점, 영업시간은 모두 실제 정보가 아닙니다.
 */

export const RAMEN_TYPE_LABELS = {
  shoyu: "쇼유",
  shio: "시오",
  miso: "미소",
  tonkotsu: "돈코츠",
  tsukemen: "츠케멘",
  mazesoba: "마제소바",
} as const;

export type RamenType = keyof typeof RAMEN_TYPE_LABELS;

export const REGIONS = [
  "서울",
  "부산",
  "대구",
  "인천",
  "광주",
  "대전",
  "울산",
  "세종",
  "경기",
  "강원",
  "충북",
  "충남",
  "전북",
  "전남",
  "경북",
  "경남",
  "제주",
] as const;

export type Region = (typeof REGIONS)[number];
export type BrothBase = "닭" | "돼지" | "소" | "해산물" | "채소";
export type BodyLevel = 1 | 2 | 3 | 4 | 5;
export type SpicinessLevel = 0 | 1 | 2 | 3 | 4 | 5;

export interface RamenShop {
  id: string;
  name: string;
  region: Region;
  district: string;
  address: string;
  lat: number;
  lng: number;
  types: RamenType[];
  signature: string;
  price: number;
  body: BodyLevel;
  spiciness: SpicinessLevel;
  bases: BrothBase[];
  tags: string[];
  rating: number;
  hours: string;
  closed: string;
  vegetarian: boolean;
  containsPork: boolean;
}

export const RAMEN_SHOPS: RamenShop[] = [
  {
    id: "demo-seoul-mapo-001",
    name: "[창작 데모] 연남 맑은면연구소",
    region: "서울",
    district: "마포구",
    address: "서울특별시 마포구 연남동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.5618,
    lng: 126.9237,
    types: ["shoyu", "shio"],
    signature: "유자 닭청탕 쇼유라멘",
    price: 11000,
    body: 2,
    spiciness: 0,
    bases: ["닭", "해산물"],
    tags: ["맑은육수", "유자향", "혼밥"],
    rating: 4.6,
    hours: "11:30-21:00",
    closed: "월요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-seoul-seongdong-002",
    name: "[창작 데모] 성수 흑마늘백탕",
    region: "서울",
    district: "성동구",
    address: "서울특별시 성동구 성수동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.5446,
    lng: 127.0561,
    types: ["tonkotsu", "mazesoba"],
    signature: "흑마늘 카라이 돈코츠라멘",
    price: 12500,
    body: 5,
    spiciness: 3,
    bases: ["돼지"],
    tags: ["카라이", "흑마늘", "진한육수"],
    rating: 4.5,
    hours: "11:00-22:00",
    closed: "연중무휴",
    vegetarian: false,
    containsPork: true,
  },
  {
    id: "demo-busan-busanjin-003",
    name: "[창작 데모] 서면 파도돈코츠",
    region: "부산",
    district: "부산진구",
    address: "부산광역시 부산진구 부전동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.1578,
    lng: 129.0596,
    types: ["tonkotsu", "shoyu"],
    signature: "멸치향 돈코츠라멘",
    price: 12000,
    body: 5,
    spiciness: 1,
    bases: ["돼지", "해산물"],
    tags: ["멸치향", "농후", "심야영업"],
    rating: 4.5,
    hours: "11:30-23:00",
    closed: "연중무휴",
    vegetarian: false,
    containsPork: true,
  },
  {
    id: "demo-busan-suyeong-004",
    name: "[창작 데모] 광안 조개시오",
    region: "부산",
    district: "수영구",
    address: "부산광역시 수영구 광안동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.1532,
    lng: 129.1188,
    types: ["shio", "shoyu"],
    signature: "바지락 시오라멘",
    price: 12500,
    body: 2,
    spiciness: 0,
    bases: ["해산물", "채소"],
    tags: ["조개육수", "깔끔함", "저염"],
    rating: 4.7,
    hours: "11:00-21:00",
    closed: "목요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-daegu-jung-005",
    name: "[창작 데모] 동성로 불향마제",
    region: "대구",
    district: "중구",
    address: "대구광역시 중구 동성로 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.869,
    lng: 128.5941,
    types: ["mazesoba", "tonkotsu"],
    signature: "청양고추 불향 마제소바",
    price: 10500,
    body: 4,
    spiciness: 4,
    bases: ["돼지", "채소"],
    tags: ["불향", "매콤함", "공깃밥"],
    rating: 4.4,
    hours: "11:30-22:00",
    closed: "연중무휴",
    vegetarian: true,
    containsPork: true,
  },
  {
    id: "demo-daegu-suseong-006",
    name: "[창작 데모] 수성 숙성미소면관",
    region: "대구",
    district: "수성구",
    address: "대구광역시 수성구 범어동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.8581,
    lng: 128.6307,
    types: ["miso", "shoyu"],
    signature: "버터옥수수 숙성미소라멘",
    price: 11500,
    body: 4,
    spiciness: 1,
    bases: ["닭", "채소"],
    tags: ["구수함", "버터", "옥수수"],
    rating: 4.3,
    hours: "11:00-20:30",
    closed: "화요일",
    vegetarian: true,
    containsPork: false,
  },
  {
    id: "demo-incheon-namdong-007",
    name: "[창작 데모] 구월 하카타실험실",
    region: "인천",
    district: "남동구",
    address: "인천광역시 남동구 구월동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.4475,
    lng: 126.7024,
    types: ["tonkotsu"],
    signature: "카라이 돈코츠라멘",
    price: 11500,
    body: 5,
    spiciness: 3,
    bases: ["돼지"],
    tags: ["카라이", "가는면", "매운돈코츠", "진한맛"],
    rating: 4.3,
    hours: "12:00-22:00",
    closed: "월요일",
    vegetarian: false,
    containsPork: true,
  },
  {
    id: "demo-incheon-yeonsu-008",
    name: "[창작 데모] 송도 청계면관",
    region: "인천",
    district: "연수구",
    address: "인천광역시 연수구 송도동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.382,
    lng: 126.6431,
    types: ["shio", "tsukemen"],
    signature: "닭청탕 레몬 시오라멘",
    price: 12000,
    body: 2,
    spiciness: 0,
    bases: ["닭", "채소"],
    tags: ["닭육수", "레몬향", "담백함"],
    rating: 4.6,
    hours: "11:30-21:00",
    closed: "수요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-gwangju-dong-009",
    name: "[창작 데모] 충장 고추미소",
    region: "광주",
    district: "동구",
    address: "광주광역시 동구 충장로 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.147,
    lng: 126.922,
    types: ["miso", "mazesoba"],
    signature: "청양고추 카라이 미소라멘",
    price: 11000,
    body: 4,
    spiciness: 4,
    bases: ["닭", "채소"],
    tags: ["카라이", "청양고추", "구수함", "채식옵션"],
    rating: 4.5,
    hours: "11:00-21:00",
    closed: "화요일",
    vegetarian: true,
    containsPork: false,
  },
  {
    id: "demo-daejeon-yuseong-010",
    name: "[창작 데모] 유성 농후츠케연구소",
    region: "대전",
    district: "유성구",
    address: "대전광역시 유성구 궁동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 36.3622,
    lng: 127.3561,
    types: ["tsukemen", "shoyu"],
    signature: "닭어패류 농후 츠케멘",
    price: 13000,
    body: 5,
    spiciness: 1,
    bases: ["닭", "해산물"],
    tags: ["굵은면", "어패류", "농후"],
    rating: 4.6,
    hours: "11:30-20:30",
    closed: "일요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-ulsan-nam-011",
    name: "[창작 데모] 삼산 훈연쇼유",
    region: "울산",
    district: "남구",
    address: "울산광역시 남구 삼산동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.5396,
    lng: 129.3326,
    types: ["shoyu", "tonkotsu"],
    signature: "훈연차슈 쇼유라멘",
    price: 12000,
    body: 3,
    spiciness: 0,
    bases: ["닭", "돼지"],
    tags: ["훈연향", "차슈", "중간농도"],
    rating: 4.4,
    hours: "11:30-21:30",
    closed: "월요일",
    vegetarian: false,
    containsPork: true,
  },
  {
    id: "demo-sejong-naseong-012",
    name: "[창작 데모] 세종 맑은닭면방",
    region: "세종",
    district: "나성동",
    address: "세종특별자치시 나성동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 36.4909,
    lng: 127.2628,
    types: ["shio", "shoyu"],
    signature: "들깨 닭청탕 시오라멘",
    price: 11500,
    body: 2,
    spiciness: 0,
    bases: ["닭", "채소"],
    tags: ["들깨향", "맑은육수", "가족식사"],
    rating: 4.5,
    hours: "11:00-20:30",
    closed: "수요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-gyeonggi-suwon-013",
    name: "[창작 데모] 수원 장독미소",
    region: "경기",
    district: "수원시",
    address: "경기도 수원시 팔달구 행궁동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.276,
    lng: 127.0163,
    types: ["miso", "mazesoba"],
    signature: "장독숙성 카라이 미소라멘",
    price: 11500,
    body: 4,
    spiciness: 3,
    bases: ["닭", "채소"],
    tags: ["카라이", "숙성미소", "매콤함", "채식옵션"],
    rating: 4.4,
    hours: "11:00-20:30",
    closed: "수요일",
    vegetarian: true,
    containsPork: false,
  },
  {
    id: "demo-gyeonggi-seongnam-014",
    name: "[창작 데모] 분당 청계탕면",
    region: "경기",
    district: "성남시",
    address: "경기도 성남시 분당구 정자동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.3787,
    lng: 127.1123,
    types: ["shio", "shoyu"],
    signature: "닭청탕 시오라멘",
    price: 12000,
    body: 2,
    spiciness: 0,
    bases: ["닭", "채소"],
    tags: ["닭육수", "담백함", "저염"],
    rating: 4.6,
    hours: "11:30-21:00",
    closed: "월요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-gangwon-chuncheon-015",
    name: "[창작 데모] 춘천 옥수수시오",
    region: "강원",
    district: "춘천시",
    address: "강원특별자치도 춘천시 효자동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 37.8813,
    lng: 127.7298,
    types: ["shio", "miso"],
    signature: "구운옥수수 시오라멘",
    price: 11000,
    body: 2,
    spiciness: 0,
    bases: ["닭", "채소"],
    tags: ["옥수수", "고소함", "담백함"],
    rating: 4.3,
    hours: "11:30-20:00",
    closed: "수요일",
    vegetarian: true,
    containsPork: false,
  },
  {
    id: "demo-chungbuk-cheongju-016",
    name: "[창작 데모] 청주 맑은간장",
    region: "충북",
    district: "청주시",
    address: "충청북도 청주시 상당구 성안동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 36.6358,
    lng: 127.4914,
    types: ["shoyu", "tsukemen"],
    signature: "숙성간장 쇼유라멘",
    price: 10500,
    body: 3,
    spiciness: 0,
    bases: ["닭", "해산물"],
    tags: ["숙성간장", "닭육수", "혼밥"],
    rating: 4.5,
    hours: "11:00-20:30",
    closed: "목요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-chungnam-cheonan-017",
    name: "[창작 데모] 천안 호두비빔면",
    region: "충남",
    district: "천안시",
    address: "충청남도 천안시 동남구 신부동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 36.8151,
    lng: 127.1139,
    types: ["mazesoba", "miso"],
    signature: "호두 탄탄풍 마제소바",
    price: 11500,
    body: 4,
    spiciness: 3,
    bases: ["돼지", "채소"],
    tags: ["호두", "고소함", "탄탄풍"],
    rating: 4.4,
    hours: "11:30-21:30",
    closed: "연중무휴",
    vegetarian: true,
    containsPork: true,
  },
  {
    id: "demo-jeonbuk-jeonju-018",
    name: "[창작 데모] 전주 누룩미소",
    region: "전북",
    district: "전주시",
    address: "전북특별자치도 전주시 완산구 중앙동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.8242,
    lng: 127.148,
    types: ["miso", "shoyu"],
    signature: "누룩숙성 미소라멘",
    price: 11500,
    body: 4,
    spiciness: 1,
    bases: ["닭", "채소"],
    tags: ["누룩", "발효향", "구수함"],
    rating: 4.6,
    hours: "11:30-21:00",
    closed: "월요일",
    vegetarian: true,
    containsPork: false,
  },
  {
    id: "demo-jeonbuk-gunsan-019",
    name: "[창작 데모] 군산 항구시오",
    region: "전북",
    district: "군산시",
    address: "전북특별자치도 군산시 영화동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.9677,
    lng: 126.7366,
    types: ["shio", "tsukemen"],
    signature: "꽃게 시오라멘",
    price: 12500,
    body: 3,
    spiciness: 1,
    bases: ["해산물", "채소"],
    tags: ["꽃게육수", "항구풍", "감칠맛"],
    rating: 4.5,
    hours: "11:00-20:00",
    closed: "화요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-jeonnam-suncheon-020",
    name: "[창작 데모] 순천만 조개츠케",
    region: "전남",
    district: "순천시",
    address: "전라남도 순천시 조례동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 34.9506,
    lng: 127.4872,
    types: ["tsukemen", "shio"],
    signature: "바지락 시오츠케멘",
    price: 12500,
    body: 3,
    spiciness: 0,
    bases: ["해산물", "채소"],
    tags: ["바지락", "해산물", "쫄깃한면"],
    rating: 4.5,
    hours: "11:00-20:30",
    closed: "화요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-gyeongbuk-gyeongju-021",
    name: "[창작 데모] 황리단 산초쇼유",
    region: "경북",
    district: "경주시",
    address: "경상북도 경주시 황남동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.8428,
    lng: 129.2117,
    types: ["shoyu", "shio"],
    signature: "산초 닭쇼유라멘",
    price: 11500,
    body: 3,
    spiciness: 1,
    bases: ["닭", "채소"],
    tags: ["산초향", "닭육수", "깔끔함"],
    rating: 4.6,
    hours: "11:30-21:00",
    closed: "수요일",
    vegetarian: false,
    containsPork: false,
  },
  {
    id: "demo-gyeongnam-changwon-022",
    name: "[창작 데모] 창원 후추백탕",
    region: "경남",
    district: "창원시",
    address: "경상남도 창원시 성산구 상남동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 35.227,
    lng: 128.6811,
    types: ["tonkotsu", "miso"],
    signature: "흑후추 돈코츠라멘",
    price: 12000,
    body: 5,
    spiciness: 2,
    bases: ["돼지"],
    tags: ["흑후추", "진한백탕", "면추가"],
    rating: 4.4,
    hours: "11:00-22:00",
    closed: "연중무휴",
    vegetarian: false,
    containsPork: true,
  },
  {
    id: "demo-jeju-jejusi-023",
    name: "[창작 데모] 제주 귤시오",
    region: "제주",
    district: "제주시",
    address: "제주특별자치도 제주시 이도동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 33.4996,
    lng: 126.5312,
    types: ["shio", "shoyu"],
    signature: "귤껍질 해산물 시오라멘",
    price: 12500,
    body: 2,
    spiciness: 0,
    bases: ["해산물", "채소"],
    tags: ["귤향", "해산물", "저염"],
    rating: 4.7,
    hours: "11:30-20:30",
    closed: "목요일",
    vegetarian: true,
    containsPork: false,
  },
  {
    id: "demo-jeju-seogwipo-024",
    name: "[창작 데모] 서귀포 화산돈코츠",
    region: "제주",
    district: "서귀포시",
    address: "제주특별자치도 서귀포시 서귀동 00 (창작 데모 주소 · 실제 매장 아님)",
    lat: 33.2541,
    lng: 126.5601,
    types: ["tonkotsu", "mazesoba"],
    signature: "흑돼지 카라이 돈코츠라멘",
    price: 13500,
    body: 5,
    spiciness: 4,
    bases: ["돼지"],
    tags: ["카라이", "흑돼지콘셉트", "매운맛", "농후"],
    rating: 4.6,
    hours: "11:30-21:30",
    closed: "월요일",
    vegetarian: false,
    containsPork: true,
  },
];
